name: Generate typings

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  generate-typings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Compile TypeScript
      run: npm run build

    - name: Import bot's GPG key for signing commits
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '["languages.d.ts", "dist"]'
        committer_email: automations@quark.bot
        committer_name: Quark Automations
