name: File validation

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  generate-typings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate typings
      run: node .github/scripts/generate-typings.js
