name: File validation

on: 
  push:
    branches-ignore:
      - weblate
  pull_request:
  workflow_dispatch:

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate all JSON files
      run: node .github/scripts/validate-json.js

  validate-slash-commands:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate Slash Command files
      run: node .github/scripts/validate-slash_commands.js
